### ISSUE TITLE
Weird "loading" message when accessing posts from the post-list.

### ISSUE THREAD

**Issue by Poliuk** [worona/worona-pwa#28]
**Solution**
- [x] Prefetch the post component.
- [x] Integrate a loading component that replaces the "loading..." message.

-----------
**Problem**
> I haven't been able to find a pattern to reproduce the bug, but it has happened to me a number of times. 

When opening a post from the home screen, sometimes the whole screen appears white and a "Loading..." plain-text message appears for an instant. (I haven't been able to make an screenshot, but it appears enough time to see it)

It looks like it something independent from the theme, and related to zeit or the pwa itself.

**Comment by Poliuk** [comment]
@luisherranz says it is related with next's `dynamic components`. There are two things to do in order to fix this:

1. Prefetch the `post` component.
2. Integrate a `loading` component that replaces the "loading..." message.

**Comment by DAreRodz** [comment]
Issue resolved in another repo: https://github.com/worona/saturn-app-theme-worona/commit/999f9f86a74c6266d3af89d838f316bd6e4b0633.
