### ISSUE TITLE
Integrate OneSignal web push notifications

### ISSUE THREAD

**Issue by Poliuk** [worona/worona-pwa#30]
- [x] **Ask to our customer how do they send web push notifications now.** (Automatically with every new post? Using the OneSignal Dashboard? With the [OneSignal WordPress Plugin](https://wordpress.org/plugins/onesignal-free-web-push-notifications/)?)
- [x] **Get our customer credentials**
- [x] **Integrate onesignal in the PWA**

> **Documentation** https://documentation.onesignal.com/docs/web-push-sdk-setup-https

**Comment by DAreRodz** [comment]
Waiting for a test in "pre-prod" before closing this issue.

**Comment by DAreRodz** [comment]
Closed in https://github.com/worona/saturn-app-theme-worona/commit/bef6dcee98624f6176f1584e47161d6e7aa8c846
